---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  ansible_args:
    # workaround for netplan apply failing inside docker
    - "-e netplan_apply_handler_command='netplan generate'"
  config_options:
    diff:
      always: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  inventory:
    links:
      group_vars: inventory/group_vars/
      host_vars: inventory/host_vars/
verifier:
  name: ansible
